# Generated by Django 6.1.1 on 2026-09-12 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ivod_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('speaker', models.CharField(db_index=True, max_length=100)),
                ('meeting', models.CharField(blank=True, max_length=300)),
                ('date', models.DateField(db_index=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('ivod_url', models.URLField(max_length=500)),
                ('source_note', models.CharField(blank=True, max_length=300)),
                ('transcript_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', '等待處理'), ('processing', '處理中'), ('ready', '已完成'), ('failed', '失敗')], db_index=True, default='pending', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date', '-published_at', '-id'],
                'indexes': [models.Index(fields=['-date', 'status'], name='articles_ar_date_2e4fe5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=300)),
                ('bullets', models.JSONField(default=list)),
                ('detail', models.TextField(blank=True)),
                ('timestamp', models.FloatField(default=0.0)),
                ('image', models.FileField(blank=True, upload_to='articles/')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='articles.article')),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('article', 'index')},
            },
        ),
    ]
