# Generated by Django 6.1.1 on 2026-09-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='gpu_job_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
