# Generated by Django 5.2.17 on 2026-09-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_article_attempts_article_gpu_job_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="brief",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
