# Generated by Django 6.1.1 on 2026-09-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_brief'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.CharField(choices=[('ly', '立法院'), ('tccc', '臺中市議會')], db_index=True, default='ly', max_length=16),
        ),
    ]
