# Generated by Django 6.1.1 on 2026-09-28 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ly', '立法院'), ('tccc', '臺中市議會')], db_index=True, max_length=16)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('party', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('term', models.CharField(blank=True, max_length=32)),
                ('photo_url', models.URLField(blank=True, max_length=500)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('needs_review', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('note', models.TextField(blank=True)),
                ('needs_review', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='party',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.membership'),
        ),
        migrations.AddField(
            model_name='membership',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='articles.person'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['source', 'name'], name='articles_me_source_3c25e0_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['source', 'external_id'], name='articles_me_source_fa0ef3_idx'),
        ),
    ]
