# Generated by Django 6.1.1 on 2026-09-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_person_membership_article_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='caucus',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='membership',
            name='role',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.CharField(choices=[('ly', '立法院'), ('tccc', '臺中市議會'), ('ntpc', '新北市議會')], db_index=True, default='ly', max_length=16),
        ),
        migrations.AlterField(
            model_name='membership',
            name='source',
            field=models.CharField(choices=[('ly', '立法院'), ('tccc', '臺中市議會'), ('ntpc', '新北市議會')], db_index=True, max_length=16),
        ),
    ]
