# Generated by Django 6.1.1 on 2026-09-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_ntpc_source_membership_role_caucus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='speaker',
            field=models.CharField(db_index=True, max_length=300),
        ),
    ]
