# Generated by Django 6.1.1 on 2026-10-01 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_speaker_longer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ly', '立法院'), ('tccc', '臺中市議會'), ('ntpc', '新北市議會')], db_index=True, max_length=16)),
                ('term', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=64)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['source', '-start_date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('source', 'name'), name='unique_session_per_source')],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.session'),
        ),
        migrations.CreateModel(
            name='ProfileStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(max_length=32)),
                ('value', models.FloatField(blank=True, null=True)),
                ('n', models.PositiveIntegerField(default=0)),
                ('percentile', models.FloatField(blank=True, null=True)),
                ('peers', models.PositiveIntegerField(default=0)),
                ('computed_at', models.DateTimeField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_stats', to='articles.person')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_stats', to='articles.session')),
            ],
            options={
                'ordering': ['session', 'person', 'indicator'],
                'constraints': [models.UniqueConstraint(fields=('person', 'session', 'indicator'), name='unique_profile_stat')],
            },
        ),
    ]
