# Generated by Django 6.1.1 on 2026-10-02 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_session_profilestat'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ly', '立法院'), ('tccc', '臺中市議會'), ('ntpc', '新北市議會')], db_index=True, max_length=16)),
                ('classifier', models.CharField(max_length=200)),
                ('labeled', models.PositiveIntegerField()),
                ('correct', models.PositiveIntegerField()),
                ('accuracy', models.FloatField()),
                ('passed', models.BooleanField(db_index=True)),
                ('mistakes', models.JSONField(blank=True, default=list)),
                ('ran_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': '議題分類評估',
                'verbose_name_plural': '議題分類評估',
                'ordering': ['-ran_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='committees',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.CharField(db_index=True, max_length=16)),
                ('secondary', models.CharField(blank=True, max_length=16)),
                ('classifier', models.CharField(db_index=True, max_length=200)),
                ('labeled_at', models.DateTimeField()),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='articles.article')),
            ],
            options={
                'verbose_name': '議題分類（模型）',
                'verbose_name_plural': '議題分類（模型）',
                'ordering': ['-labeled_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TopicLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.CharField(blank=True, db_index=True, max_length=16)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('labeled_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='topic_label', to='articles.article')),
            ],
            options={
                'verbose_name': '議題標註',
                'verbose_name_plural': '議題標註',
                'ordering': ['article__source', 'article_id'],
            },
        ),
    ]
