# Generated by Django 6.1.1 on 2026-10-02 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_profilestat_classifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classifier', models.CharField(max_length=200)),
                ('labeled', models.PositiveIntegerField()),
                ('correct', models.PositiveIntegerField()),
                ('accuracy', models.FloatField()),
                ('passed', models.BooleanField(db_index=True)),
                ('mistakes', models.JSONField(blank=True, default=list)),
                ('ran_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': '追問判斷評估',
                'verbose_name_plural': '追問判斷評估',
                'ordering': ['-ran_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask_index', models.PositiveIntegerField()),
                ('request', models.TextField()),
                ('deadline_text', models.CharField(max_length=300)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('quote', models.TextField(blank=True)),
                ('classifier', models.CharField(blank=True, db_index=True, max_length=200)),
                ('checked', models.JSONField(blank=True, default=list)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='articles.article')),
                ('followed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_of', to='articles.article')),
            ],
            options={
                'verbose_name': '追問（模型）',
                'verbose_name_plural': '追問（模型）',
                'ordering': ['due_date', 'id'],
                'constraints': [models.UniqueConstraint(fields=('article', 'ask_index'), name='unique_followup_per_ask')],
            },
        ),
        migrations.CreateModel(
            name='FollowUpLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask_index', models.PositiveIntegerField()),
                ('request', models.TextField(blank=True)),
                ('followed', models.BooleanField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('labeled_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_labels', to='articles.article')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='articles.article')),
            ],
            options={
                'verbose_name': '追問標註',
                'verbose_name_plural': '追問標註',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('article', 'ask_index', 'candidate'), name='unique_followup_label')],
            },
        ),
    ]
