# Generated by Django 6.1.1 on 2026-10-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_followups'),
    ]

    operations = [
        migrations.CreateModel(
            name='LyBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=32, unique=True)),
                ('term', models.PositiveSmallIntegerField()),
                ('session_number', models.PositiveSmallIntegerField()),
                ('name', models.TextField()),
                ('status', models.CharField(blank=True, max_length=64)),
                ('proposers', models.JSONField(blank=True, default=list)),
                ('cosigners', models.JSONField(blank=True, default=list)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('proposed_on', models.DateField(blank=True, null=True)),
                ('synced_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': '立法院委員提案',
                'verbose_name_plural': '立法院委員提案',
                'ordering': ['-proposed_on', '-bill_no'],
                'indexes': [models.Index(fields=['term', 'session_number'], name='articles_ly_term_cda16c_idx')],
            },
        ),
        migrations.CreateModel(
            name='LyMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('kind', models.CharField(choices=[('plenary', '院會'), ('committee', '委員會')], db_index=True, max_length=16)),
                ('term', models.PositiveSmallIntegerField()),
                ('session_number', models.PositiveSmallIntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('dates', models.JSONField(blank=True, default=list)),
                ('name', models.CharField(max_length=300)),
                ('units', models.JSONField(blank=True, default=list)),
                ('attendees', models.JSONField(blank=True, default=None, null=True)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('synced_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': '立法院會議',
                'verbose_name_plural': '立法院會議',
                'ordering': ['-date', 'code'],
                'indexes': [models.Index(fields=['term', 'session_number'], name='articles_ly_term_1e6575_idx')],
            },
        ),
        migrations.CreateModel(
            name='LyVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('term', models.PositiveSmallIntegerField()),
                ('session_number', models.PositiveSmallIntegerField()),
                ('meeting_code', models.CharField(db_index=True, max_length=64)),
                ('voted_at', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('topic', models.TextField(blank=True)),
                ('yes', models.JSONField(blank=True, default=list)),
                ('no', models.JSONField(blank=True, default=list)),
                ('abstain', models.JSONField(blank=True, default=list)),
                ('voters', models.JSONField(blank=True, default=list)),
                ('synced_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': '立法院記名表決',
                'verbose_name_plural': '立法院記名表決',
                'ordering': ['-date', '-code'],
                'indexes': [models.Index(fields=['term', 'session_number'], name='articles_ly_term_ce820d_idx')],
            },
        ),
    ]
