# Generated by Django 6.1.1 on 2026-10-02 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_ly_records'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillTopicEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classifier', models.CharField(max_length=200)),
                ('labeled', models.PositiveIntegerField()),
                ('correct', models.PositiveIntegerField()),
                ('accuracy', models.FloatField()),
                ('passed', models.BooleanField(db_index=True)),
                ('mistakes', models.JSONField(blank=True, default=list)),
                ('ran_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': '議案分類評估',
                'verbose_name_plural': '議案分類評估',
                'ordering': ['-ran_at', '-id'],
            },
        ),
        migrations.AlterField(
            model_name='profilestat',
            name='classifier',
            field=models.CharField(blank=True, default='', max_length=401),
        ),
        migrations.CreateModel(
            name='BillTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.CharField(db_index=True, max_length=16)),
                ('secondary', models.CharField(blank=True, max_length=16)),
                ('classifier', models.CharField(db_index=True, max_length=200)),
                ('labeled_at', models.DateTimeField()),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='articles.lybill')),
            ],
            options={
                'verbose_name': '議案分類（模型）',
                'verbose_name_plural': '議案分類（模型）',
                'ordering': ['-labeled_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BillTopicLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.CharField(blank=True, db_index=True, max_length=16)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('labeled_at', models.DateTimeField(blank=True, null=True)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='topic_label', to='articles.lybill')),
            ],
            options={
                'verbose_name': '議案議題標註',
                'verbose_name_plural': '議案議題標註',
                'ordering': ['bill_id'],
            },
        ),
    ]
