# Generated by Django 6.1.1 on 2026-09-19 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0002_article_attempts_article_gpu_job_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('quote', models.TextField()),
                ('timestamp', models.FloatField(default=0.0)),
                ('kind', models.CharField(choices=[('law_article', '法條內容'), ('bill_content', '議案內容'), ('bill_status', '議案進度')], max_length=20)),
                ('statement', models.TextField()),
                ('subject', models.JSONField(blank=True, default=dict)),
                ('verdict', models.CharField(choices=[('supported', '相符'), ('partial', '部分相符'), ('contradicted', '不符'), ('unverifiable', '無法查證')], db_index=True, max_length=16)),
                ('method', models.CharField(choices=[('numeric', '數字比對'), ('model', '模型判讀'), ('none', '未比對')], max_length=16)),
                ('rationale', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('auto', '自動發佈'), ('pending_review', '待審核'), ('approved', '已核准'), ('rejected', '已駁回')], db_index=True, default='auto', max_length=16)),
                ('reviewer_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='articles.article')),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('article', 'index')},
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('source', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=300)),
                ('official_url', models.URLField(blank=True, max_length=1000)),
                ('api_url', models.URLField(blank=True, max_length=1000)),
                ('excerpt', models.TextField(blank=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='factchecks.claim')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='FactCheckRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待查核'), ('processing', '查核中'), ('done', '已完成'), ('failed', '失敗')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('gpu_job_id', models.CharField(blank=True, max_length=64)),
                ('error', models.TextField(blank=True)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factcheck_run', to='articles.article')),
            ],
        ),
    ]
